apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: tabletoprank
spec:
  ports:
    - port: 8080
      nodePort: 31874
  selector:
    app: tabletoprank
    tier: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: tabletoprank
spec:
  selector:
    matchLabels:
      app: tabletoprank
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tabletoprank
        tier: backend
    spec:
      containers:
      - image: tabletoprank/api:latest
        name: api
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: password
        ports:
        - name: api
          containerPort: 8080
