apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: tabletoprank
spec:
  ports:
    - port: 80
      nodePort: 31875
  selector:
    app: tabletoprank
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: tabletoprank
spec:
  selector:
    matchLabels:
      app: tabletoprank
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tabletoprank
        tier: frontend
    spec:
      containers:
      - image: tabletoprank/web:latest
        name: web
        ports:
        - name: web
          containerPort: 80
